Sprint 2
elagarrigue/AyDS21-JK-Hera1 pull request #2
Opened 2021-05-17 23:59 UTC by KarinaSchimpfle

2021-05-19 00:33 UTC, kevschweitzer requested changes

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/DataBase.kt
> +class DataBaseImp : DataBase {
deberia ser internal y con un nombre mas representativo

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/DataBase.kt
> +interface DataBase{
Nombre más representativo

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/DataBase.kt
> +    override fun createNewDatabase() {
Separar en métodos el openConnection y closeConnection para la DB. Utilizar el siguiente esquema

openConnection()
doSomething()
closeConnection()

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/NYTimesAPI.kt
> +
Borrar linea de más

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private lateinit var textPane2: JTextPane
textPane2 no es un nombre representativo

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    fun getSongInfo(song: Song) {
Este método es muy largo y tiene muchas responsabilidades.

- Abstraigan en un método aparte lo que es el algoritmo del repositorio (eso es una responsabilidad)
- Una vez obtenido el dato buscado pueden darle formato (otra responsabilidad)
- Finalmente pueden mostrarlo en pantalla

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                    val abstract = getJsonElement(response, "abstract")
abstract es una palabra reservada

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                    text = replaceBars(abstract)
asignar dos veces seguidas a la misma variable no es clean

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                    initFullArticleListener(url)
El listener deberia inicializarse una sola vez, no cada vez que se busca. Inicializarlo al inicio. Para eso deberan (por ahora) guardar la URL en una variable

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/DataBase.kt
> +        const val url = "jdbc:sqlite:./dictionary.db"
nombres de constantes van todo en mayusc

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/DataBase.kt
> +                    statement.executeUpdate("create table artists (id INTEGER PRIMARY KEY AUTOINCREMENT, artist string, info string, source integer)")
Crear constantes para los nombres de las columnas y el nombre de la tabla

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        textPane2.maximumSize = Dimension(600, 400)
Utilizar constantes para las dimensiones que se utilizan en todas las vistas (ej. 600)

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        val jobj = gson.fromJson(callResponse.body(), JsonObject::class.java)
jobj?

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        val gson = Gson()
Esta variable no es necesaria porque usan el objeto una sola vez. Pueden hacerlo inline

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        } catch (e: Exception) {
catch vacio?

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun replaceBars(abstract: JsonElement) = abstract.asString.replace("\\n", "\n")
abstract es una palabra reservada

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun isInDataBase(text: String?) = text != null
Ver si un string es distinto de null no es "ver si esta en la base de datos". Lo que pueden hacer en todo caso es agregar la linea anterior a esta llamada en este metodo.

```suggestion
    private fun isInDataBase(text: String?): Boolean {
            var text = dataBase.getInfo(song.artistName)
            return text != null
    }
```

Además text debería tener otro nombre más representativo

2021-05-19 00:33 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            val win = OtherInfoWindow(ArticleDataHandlerImp(initNYTimesAPI()), DataBaseImp())
Podrian usar una de las bondades de Kotlin

return  OtherInfoWindow(ArticleDataHandlerImp(initNYTimesAPI()), DataBaseImp()).also{
    it.buildUi()
}

2021-05-20 19:44 UTC, kevschweitzer commented
Antes que nada chicos fijense que tienen conflictos. Van a tener que actualizar este branch contra el master

2021-05-20 23:36 UTC, kevschweitzer requested changes

2021-05-20 23:36 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private val apiNYTimesAPI = initNYTimesAPI()
Siendo que ya estan inyectando la base de datos y el helper podrian inyectar la API

2021-05-20 23:36 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getSongInfoFromRepository(song: Song): String {
El metodo deberia llamarse solo getSongInfo

2021-05-20 23:36 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            dataBase.saveArtist(song.artistName, songInfoFormatted)
2 cosas. Primero el guardado de la información es parte del algoritmo del repositorio (en caso de no estar en la BD se llama al servicio y se guarda el resultado antes de retornar). Lo segundo es que lo que se debe guardar en la base de datos es el dato sin formatear ya que el formato es parte de la vista y puede cambiar

2021-05-20 23:36 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        dataBase.createNewDatabase()
createNewDatabase deberia hacerse al inicializar solamente

2021-05-20 23:36 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                val abstr = getJsonElement(response, "abstract")
El dato que llega al repositorio desde el servicio (o al metodo del repositorio por ahora)  ya deberia estar deserializado. Eso no es responsabilidad del repositorio. Deberian tener algo asi

```
var info = database.getInfo()
if(info != null) {
    marcarComoYaBuscado()
} else {
    info = nytimesApi.getInfo()
    database.save(info)
}

return info
```

2021-05-20 23:36 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            val songInfoFormatted = songInfoDescriptionHelper.getSongInfoDescriptionText(replaceBars(songInfo), song)
replaceBars se puede tomar como parte de "darle formato". Deberia estar directamente como primer paso en getSongInfoDescriptionText

2021-05-20 23:36 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        return songInfo ?: "ERROR"
Si "ERROR" es lo que quiero mostrar en la vista cuando pasa algo que no me deja obtener un resultado no deberia ser responsabilidad del repositorio definir ese texto. Por ahora pueden retornar algo vacio o nulo y cuando chequeen el resultado deciden que mensaje poner

2021-05-20 23:36 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/SongInfoDescriptionHelper.kt
> +
Lineas de más

2021-05-20 23:36 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/DataBase.kt
> +interface LocalSongRepository {
Esto no es un Repository, esta en la database. Pongan el nombre OtherInfoDatabase por ejemplo. Además comparen como está implementada la BD en el otro paquete, van a ver que hereda de SqlDB, una clase que ya tiene implementados openConnection(), closeConnection() y una propiedad `statement` que pueden utilizar para evitar crearla y setearla cada vez que la usan. Fijense en el otro paquete como se aplica el esquema

openConnection()
dotSomething()
closeConnection()

2021-05-20 23:36 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        const val WIDTH = 600
WIDTH de que?

2021-05-22 03:06 UTC, julian-pineiro commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getSongInfoFromRepository(song: Song): String {
Hola Kevin! Ya tenemos un método llamado getSongInfo al que getSongInfoFromRepository es auxiliar, y sobrecargaría la función. ¿Es preferible cambiarlo de todas formas? Una alternativa que se me ocurre sería llamarlo FetchSongInfo o getFromDatabase ya que busca a la base de datos el valor.

2021-05-22 03:15 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getSongInfoFromRepository(song: Song): String {
Bien. El metodo del repositorio deberia llamarse igual getSongInfo. Al que inicializa el thread pueden ponerle otro nombre, fetchSongInfo estaria bien para ese

2021-05-22 03:21 UTC, julian-pineiro commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getSongInfoFromRepository(song: Song): String {
Excelente! Gracias!

2021-05-23 00:08 UTC, kevschweitzer requested changes
Bien chicos, solo unos pequeños detalles más y ya estaríamos para mergear

2021-05-23 00:08 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            if (songInfo != null) {
Si van a usar null para tomarlo como error de songInfo deberian poner un else para mostrar "No se ha podido recuperar más información" o algo asi

2021-05-23 00:08 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                val abstr = getJsonElement(response, "abstract")
Veo resuelta la correción anterior pero no veo que la hayan hecho

El dato que llega al repositorio desde el servicio (o al metodo del repositorio por ahora) ya deberia estar deserializado. Eso no es responsabilidad del repositorio. Deberian tener algo asi
```
var info = database.getInfo()
if(info != null) {
    marcarComoYaBuscado()
} else {
    info = nytimesApi.getInfo()
    database.save(info)
}

return info
```

2021-05-23 00:08 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        return songInfo ?: null
Este ?: null no es necesario (es mas, tienen un warning). Si se ejecuta lo que está despues de ?: quiere decir que songInfo es null asi que nunca tiene sentido hacer ?: null.

2021-05-23 23:04 UTC, kevschweitzer approved these changes

2021-05-23 23:04 UTC, merged