Sprint 3
elagarrigue/AyDS21-JK-Hera1 pull request #3
Opened 2021-06-09 18:21 UTC by KarinaSchimpfle

Estamos trabados con una parte, pero decidimos hacer el pull request para saber al menos si el resto está bien y estar seguros de que no estamos trabajando sobre una base que está mal.

2021-06-10 01:39 UTC, kevschweitzer requested changes
- Eliminar el paquete fullLogic. Debajo de moreDetails deben estar directamente las carpetas del mvc

Diagrama de clases:
- Darle dirección a las flechas
- Que las flechas no vayan de clase a clase cuando salen del paquete. Mejor de paquete a paquete. Asi en vez de ir  desde `MoreDetailsView` a `MoreDetailsController` va a ir desde el paquete `view` al paquete `controller`. Las flechas que se mantienen dentro del paquete si mantenerlas
- La base de datos va dentro de una carpeta local en el Repository (acomodar esto en el proyecto).
- Representar los observers mediante lineas punteadas para que quede bien marcado el MVC.
- Poner todo el diagrama dentro del paquete `moredetails` y hacer otro paquete que se llame `home` y que tenga una flecha hacia `moredetails` (para marcar de donde se llega a ese diagrama)

2021-06-10 01:39 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/model/entities/ArticleData.kt
> +data class ArticleDataImpl(
Cuando se habla de entidades no es buena opcion usar Impl.  `ArticleData` como interfaz y `NYTArticleData` como implementación podria ser. Además ver el patrón Null Object que es lo que se usa en Home con el nombre de `EmptySong`

2021-06-10 01:39 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/model/repository/InfoSongRepository.kt
> +    fun getSongInfo(song: Song): ArticleData?
Chequear como usar el patrón null object (nombrado en el comment anterior) evita el ArticleData nullable

2021-06-10 01:39 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/model/repository/InfoSongRepository.kt
> +                dataBase.saveArtist(song.artistName, songInfo)
Faltaria tener en cuenta el update

2021-06-10 01:39 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/model/repository/InfoSongRepository.kt
> +    private fun getSongInfoFromAPI(song: Song): ArticleData {
De aca para abajo no va dentro del repositorio. Ver `SpotifyToSongResolver`

2021-06-10 01:39 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/view/MoreDetailsUIView.kt
> +        updateArticleURL(value.articleURL)
Solamente el URL tienen que actualizar? Y los demás datos de ArticleData?

2021-06-10 01:39 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/view/MoreDetailsUIView.kt
> +        with(moreDetailsUiComponents) {
No veo la ventaja del with acá

2021-06-10 01:39 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/view/MoreDetailsUIView.kt
> +    private fun openFullArticleAction() {
Una función que llama a otra función es una indirección innecesaria. Poner todo en una función directamente

2021-06-10 01:39 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/view/MoreDetailsUiComponents.kt
> +        frame = JFrame(WINDOW_TITLE)
Aca podrian usar un `JFrame(WINDOW_TITLE).apply {}`

2021-06-12 03:04 UTC, kevschweitzer requested changes
Hola chicos:

Les subi un pequeño fix por el tema del servicio. Un problema con el fetchSongInfo hacía que no se ejecute nunca la llamada. Seguramente tiene que ver con un orden entre que se dispara el evento y se pone a observar. Por ejemplo si el evento se dispara antes de que el observer esté listo puede no dispararse, asi que lo pasé al init del Controller.

Otra cosa que cambie (que igual como no les disparaba el observer no se estaban dando cuenta) es que cuando escuchan el evento del model deben ademas de actualizar el estado llamar al método `updateArticlePreview` que no se estaba llamando.

Fijense que cambie los nombre de SongInfoDescriptionHelper a ArticleDescriptionHelper que es mas representativo. No deberian tener referencias a la clase Song en el paquete moredetails y la vi en varios lados, revisen eso, tienen varios nombres cruzados con Song ahi.

El codigo igual no anda porque tienen varios TODO en la resolución de los datos del servicio (en `NYTimesAPIToArticleDataResolver`) por lo que me tira un crash la app como que hay un método aún no implementado. Eso continuenlo ustedes. Fijense que no necesitan `id` para el article, el `source` por ahora es 1, el `artistName` es el parametro de busqueda asi que lo tienen por parametro para agregarlo a la entidad ArticleData.

Fijense tambien el tema de alreadySearched que veo que lo ponen en la base de datos. No va a la base eso, es para uso de la vista, chequeen como en home se setea en el repository en la entidad pero no se guarda en la DB.

Creo que con eso ya les quedaría destrabada la continuación de las correciones. Cualquier cosa me avisan

Pd: Ahora veo que hice el commit en spaninglish. Disculpen que les haya roto su precioso history en inglés. En la empresa donde trabajo hay mucho spaninglish dando vuelta 👎

2021-06-12 03:58 UTC, kevschweitzer commented
Me quede viendo unas cosas y tienen temas gráficos tambien, ya que nunca les carga ni un Label. Cuando algo andaba antes y ahora dejó de hacerio es una buena practica volver a la version anterior y ver que puede haber pasado. En este caso miré el master y vi que al método `addContentPane()` que está en `MoreDetailsUiComponent` le falta la linea `frame.contentPane = contentPane` por lo que, obviamente, nunca añadían el contentPane y nunca veían nada. Con eso anda

2021-06-13 15:55 UTC, kevschweitzer requested changes
Ahora si tiene un poco más de forma jajaja. En cuanto a mejorias de codigo les queda poco, pero fijense en la funcionalidad que les dije en el ultimo comentario

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/controller/MoreDetailsController.kt
> +                MoreDetailsUiEvent.OpenView -> fetchSongInfo()
Ya no se usa. Dejar un solo evento (aunque parezca que el when no tenga sentido)

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/controller/MoreDetailsController.kt
> +        println("Abrir link "+ moreDetailsView.uiState.articleURL)
Eliminar print

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/ArticleRepository.kt
> +                println("Buscando desde la api... con artistName: "+artistName)
Eliminar print

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/ArticleRepository.kt
> +    private fun completeArticleDataValues(articleData: NYTArticleData, artistName: String): NYTArticleData {
No hace falta este método, se puede hacer inline

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/NYTimesAPI/NYTimesAPIToArticleDataResolver.kt
> +                NYTArticleData(
Usen valores por defecto en la clase NYTArticleData para no tener que completar desde aca con vacio. Van a tener que usar `named parameters` para poder instanciarlo.  Fijense aca si tienen dudas https://kotlinlang.org/docs/functions.html#default-arguments

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/NYTimesAPI/NYTimesAPIToArticleDataResolver.kt
> +private fun JsonObject.getArtistName(): String {
Cambiando el comentario anterior estos e iria

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/NYTimesAPI/NYTimesArticleService.kt
> +
Linea de más

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/NYTimesAPI/NYTimesArticleService.kt
> +
Lineas de más

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/MoreDetailsDataBase.kt
> +            println("La base de datos me retornó: " + rs.toString())
Eliminar print

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/ResultSetToArticleDataMapper.kt
> +                    alreadySearched = resultSet.getBoolean(ARTISTS_TABLE_ALREADY_SEARCHED),
2 cosas con respecto a alreadySearched

1- No hay que guardarlo en la base de datos: Guardar en la base de datos un valor que signifique "está en la base de datos" no tiene mucho sentido. El alreadySearched solo se mete en el objeto de ArticleData para ser usado del repositorio para arriba (hacia la vista). Fijense en home
2- Mantengan un solo nombre. En home se llama isLocallyStored y aca alreadySearched. Elijan uno

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/TableArtistIds.kt
> +const val DB_URL = "jdbc:sqlite:./dictionary.db"
Cambiar el nombre de la DB. `dictionary.db` no es un nombre que represente articulos de NYT

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/ArticleDescriptionHelper.kt
> +        if (article.alreadySearched) {
Este if podria estar dentro del metodo`markAsAlreadySearched` y quedarles

```
 return if article.alreadySearched [*] + text else text
```

Al darle esta funcionalidad cambienle el nombre igual ya que ahora no siempre hace markAsAlreadySearched

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +        println("Vista inicializada")
Eliminar print

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +        println("Estado UIState actualizado")
Eliminar print

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +        println(value.toString())
eliminar print

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +
linea de más

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUiComponents.kt
> +            println("Componentes de vista inicializados")
Eliminar print

2021-06-13 15:55 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsViewModule.kt
> +    val moreDetailsView: MoreDetailsUIView = MoreDetailsUIViewImpl(
Fijense que pasa cuando abren la ventana `more details`, la cierran y le vuelven a dar a `more details`. Ahi no aparece la ventana. Mirando un poco creo que debe ser que este moreDetailsView se crea una sola vez asi que nunca mas se ejecutan los metodos init. Cheequenlo a ver si lo pueden arreglar. Pueden sacar el `val moreDetailsView` de aca por ejemplo y crear una nueva cada vez que sea requerida. Eso puede ser un fix (o al menos una parte)

2021-06-13 16:01 UTC, kevschweitzer commented
Sobre el diagrama UML

- Falta la flecha punteada de observer que va desde view a controller
- Revisar los nombres. InfoSongRepository no se llama asi ahora parece
- Hacer conexiones de `conoce a` dentro de los paquetes. Ej: repository conoce a local y external. Estas flechas deben llegar al paquete, no a la clase en si. Despues dentro de los paquetes en si tambien faltarian flechas. Ej: MoreDetailsUiView conoce al Helper (cuyo nombre esta mal tambien)

2021-06-13 23:58 UTC, TomasDiez99 commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsViewModule.kt
> +    val moreDetailsView: MoreDetailsUIView = MoreDetailsUIViewImpl(
Es un error o una feature que no haya limites para abrir ventanitas de more details? Todas son funcionales

2021-06-14 23:57 UTC, kevschweitzer approved these changes
Apruebo con 3 comentarios para que miren:

1. Fijense que cada vez que abren moreDetails el print se imprime una vez más. Esto es porque la instancia de MoreDetailsModel nunca se elimina y cada vez que se abre una nueva ventana se hace un subscribe. No se si lo van a poder solucionar igual pero para que lo tengan en cuenta. Deberian desuscribir el observer al cerrar la ventana.

2. Fijense que openWindow() en MoreDetailsUIComponents no lo están llamando nunca y tienen el buildUI() en el init

3. Los URL dicen cualquier cosa que no tiene nada que ver con el artista. No se si esto estaba asi o tocaron algo pero revisenlo si pueden

2021-06-14 23:57 UTC, merged