Sprint 4
elagarrigue/AyDS21-JK-Hera1 pull request #4
Opened 2021-06-27 02:23 UTC by KarinaSchimpfle

2021-06-28 12:28 UTC, kevschweitzer requested changes
- Acomodar UML según los nuevos cambios (que la flecha que va al nuevo modulo salga directo de la interface CardRepository). Ver tambien si hay cambios de nombres

- Falta un readme en el repositorio externo (importante para lo que vayan a usar su servicio)

2021-06-28 12:28 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/TableArtistIds.kt
> +const val DB_URL = "jdbc:sqlite:./dictionary.db"
Volvieron para atras el nombre de la DB? Podria ser cards.db ahora

2021-06-28 12:28 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUiState.kt
> +    val source: Int = 1,
- A la UI le interesa el texto del source, no un número. Deberian resolver que texto mostrar para el servicio al momento de actualizar el UIState

- alreadySearched no deberia estar. Deberian setear una descripción con o sin asterisco directamente en al momento de actualizar el UIState

2021-06-28 12:28 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUiState.kt
> +object SourceURLLogoNYTimesAPI{
El URL de la imagen del source deberia venir desde el Servicio

2021-06-28 13:47 UTC, kevschweitzer commented
Otros comentarios:

- isLocallyStored y Source y artistName  no deberian estar en la entidad del submodulo
- la linea `nyTimesApi.getArtistInfo(artist).execute()` en el submodulo puede tirar una excepción. Decidan si quieren lanzarla o catchearla y retornar null, pero especifiquen esto en el readme para uso de las demás comisiones

2021-06-28 13:59 UTC, kevschweitzer requested changes

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/MoreDetailsModel.kt
>      fun getArticle(artistName: String)
getCard

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/MoreDetailsModel.kt
> +    private val articleInfoSubject = Subject<Card>()
cardSubject

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/CardRepository.kt
> +        var articleCard = dataBase.getArtistInfo((artistName))
solo card, no es articleCard. Corregir en toda la clase

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/MoreDetailsDataBase.kt
>  interface MoreDetailsDataBase {
- cambiar a CardDatabase
- saveCard
- getCard

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/MoreDetailsDataBase.kt
> +    fun saveArtist(artistName: String, articleData: CardImpl)
articleData no, es card

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/MoreDetailsDataBase.kt
> +            insertArtist(artistName, articleData)
insertCard

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/MoreDetailsDataBase.kt
> +    private fun executeGetArtistInfo(artist: String): CardImpl? {
executeGetCard

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/MoreDetailsDataBase.kt
>          if (tableCreated(ARTISTS_TABLE)) {
CARD_TABLE

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/ResultSetToCardMapper.kt
> +                    description = resultSet.getString(ARTISTS_TABLE_INFO),
ver las referencias ARTIST en el archivo de constantes

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/SqlTableArtistQueries.kt
> +    fun getInsertArtistQuery(artistName: String, articleData: CardImpl): String
getInsertCardQuery

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/SqlTableArtistQueries.kt
>  interface SqlTableArtistQueries {
SqlTableCardQueries

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/SqlTableArtistQueries.kt
>      fun getSelectGetArtistInfoQuery(artist: String): String
getSelectCardQuery

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/CardDescriptionHelper.kt
> +    private fun markIfIsAlreadySearched(article: Card, text: String): String {
card: Card

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +    fun updateArticlePreview(article: Card)
update`Card`Preview(`card`: Card)

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +    private val articleDescriptionHelper: CardDescriptionHelper,
cardDescriptionHelper

2021-06-28 13:59 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +    private fun updateArticleUiState(value: Card) {
update`Card`UIState(`card`: Card)

2021-06-28 13:59 UTC, kevschweitzer commented
Les dejé algunos comentarios más

2021-06-30 23:17 UTC, kevschweitzer requested changes
Comentarios del submodulo 

- Al usuario le interesa la API, osea lo que retorne la interfaz y como usarla. Decir que la excepcion la lanza checkDocs no es relevante para el usuario. Si esa excepcion no se catchea y se lanza a través del metodo getArticle() deberian decir que getArticle lanza la excepción
- tienen 3 clases para representar una entidad, una de las cuales no se usa (EmptyCard). Con una sola clase `NYTArticleData` alcanza

Comentarios generales
- subieron el archivo de la base de datos card.db. Fijense porque se les subio porque no deberia
- En el UML pusieron todo lo de la API adentro del paquete exceptions. Eso no está ahi

2021-06-30 23:17 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/entities/Card.kt
> +    open val source: Int,
source debe ser un enumerado. En este caso con tipos EMPTY y NYTIMES. Para guardarlo en la base de datos tienen que obtener el ordinal (value.ordinal) de ese enumerado (ya que la db debe guardar int) y para recuperarlo de la base de datos deben usar la forma inversa que seria algo asi

`Source.values()[getInt(getColumnIndexOrThrow(SOURCE_COLUMN))]`

2021-06-30 23:17 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/entities/Card.kt
> +    source = 1,
Aca va a ser EMPTY

2021-06-30 23:17 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/CardRepository.kt
> +        return Card(card.description, card.source, card.articleURL, true, card.sourceLogoURL)
Pueden usar la función copy como hacen con al UIState en vez de crear una nueva

2021-06-30 23:17 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/TableArtistIds.kt
> +const val CARD_TABLE = "artists"
aca podrian cambiar los nombres tambien. CARD_TABLE tiene value "artists" y demás

2021-06-30 23:17 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUiState.kt
> +    val source: Int = 1,
Source tiene que ser un String aca

2021-07-01 00:34 UTC, TomasDiez99 commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/CardRepository.kt
> +        return Card(card.description, card.source, card.articleURL, true, card.sourceLogoURL)
La entidad Card ahora no es una data class (porque 'data' no se puede superponer con 'open'). Entonces no tiene el método copy implementado. Te parece si le seteamos la property isLocallyStored en true? Estaría modificando el parámetro en vez de retornar una copia modificada

2021-07-01 00:35 UTC, TomasDiez99 commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/TableArtistIds.kt
> +const val CARD_TABLE = "artists"
No te entendí bien el cambio de nombre que sería mejor. Vos decís que los values de estas constantes tengan incluída la palabra 'card' o algo así?

2021-07-01 17:38 UTC, kevschweitzer requested changes

2021-07-01 17:38 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +    private fun updateCardUiState(card: Card) {
Ultimo comentario. Creo que no entendieron bien la idea del UIState. Cuando les dije que source tenia que ser un String es porque lo que ustedes van a mostrar es "Info from New York Times" o algo asi. Por lo tanto a la vista solo le interesa ese texto, nada más. La idea entonces es que cuando ustedes actualizan la UIState le brinden lo que la vista necesita. En este caso no deberian asignarle card.source.toString() al source sino que directamente le deberian asignar `cardToSourceStringFactory.get(card).map()`. De esa manera updateSource solo tomaria el valor asignado a UIState y lo asignaria a la label, nada más (evitando asi pasarle el card por parametro tambien).

Exactamente lo mismo deberian hacer con la description. Asignenle el texto ya formateado al UIState y en el metodo `updateCardPreview` solo toman el valor y se lo asignan al label (borrar tambien el parametro card)

2021-07-01 19:19 UTC, kevschweitzer approved these changes

2021-07-01 19:19 UTC, merged