Sprint 5
elagarrigue/AyDS21-JK-Hera1 pull request #5
Opened 2021-07-04 04:58 UTC by KarinaSchimpfle

Dado que no pudimos resolver el problema con el iterator, cambiamos la lógica de manera que ahora usa indices, sabemos que faltan cambiar cosas en MoreDetailsView, pero decidimos hacer el pull request para saber si el resto de las cosas van bien encaminadas (tal vez el iterator no nos funciona porque hay alguna otra cosa mal).

2021-07-04 19:55 UTC, TomasDiez99 commented
Nos dimos cuenta de que hay un error al traer las cards desde la base de datos! Estuvimos trackeando el error y parece que los saves se hacen correctamente pero cuando hacemos el get de la base de datos, solo nos trae la card de NYTimes.

2021-07-06 23:50 UTC, kevschweitzer requested changes
Comentarios sobre el diagrama UML

- La implementación del los servicios que no son de ustedes no deberia estar
- Agregar las 3 implementaciones del Proxy. Para ser mas especificos en este caso si agregamos la implementación
- Cuando agreguen los proxies saquen las flechas directamente desde cada proxy hasta las librerias
- Agregar un asterisco a la flecha desde broker a proxy para especificar que es una relación 1 a muchos

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/controller/MoreDetailsController.kt
> +    private var currentUiStateIndex: Int = 0
- el index deberia estar en el UIState
- el UIState deberia tener un metodo getNextCard() que actualice el index al siguiente elemento y devuelva la card correspondiente

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/controller/MoreDetailsController.kt
> +        println("Size de la lista: " + moreDetailsView.cardsUiStates.size)
Eliminar este método. Cuando tienen un evento de Next actualizan la vista con getNextCard de la UI

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/MoreDetailsModel.kt
> +    fun cardsObservable(): Observable<MutableList<Card>>
no necesitan modificar la lista asi que deberia ser solo List, no MutableList

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/MoreDetailsModelModule.kt
> +    private val infoSongRepository = CardRepositoryImpl(dataBaseMoreDetails,broker)
```suggestion
    private val infoSongRepository = CardRepositoryImpl(dataBaseMoreDetails, broker)
```

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/CardRepository.kt
> +        if (cardList.size > 0) {
cardList.isNotEmpty()

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/CardRepository.kt
> +            for (card in cardList)
cardList.forEach{} y eliminar print

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/CardRepository.kt
> +                for (card in cardList)
forEach

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/CardRepository.kt
> +                println("Entré al broker")
Eliminar print

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/CardRepository.kt
> +        return cardList ?: mutableListOf(EmptyCard)
Mejor usar lista vacia como Empty

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/Broker.kt
> +    fun getCardList(artistName: String): MutableList<Card>
```suggestion
    fun getCardList(artistName: String): List<Card>
```

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/Broker.kt
> +    private val proxyList: MutableList<Proxy>
```suggestion
    private val proxyList: List<Proxy>
```

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/Broker.kt
> +    private var cardList: MutableList<Card> = mutableListOf()
Esta lista podria ser local al metodo

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/BrokerModule.kt
> +    private val listProxy: MutableList<Proxy> = mutableListOf(
```suggestion
    private val listProxy: MutableList<Proxy> = listOf()
```

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyLastFMData.kt
> +            Card(
El mapeo en cada Proxy deberia ser un metodo aparte

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyLastFMData.kt
> +        val lastFM = lastFmDataService.getCardInfo(artistName)
Todas las librerias devuelven null cuando hay error? Chequeen si alguna no especifica que se lanza alguna exception (que deberian catchear)

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/CardDataBase.kt
> +    fun getCardInfoList(artist: String): MutableList<Card>
```suggestion
    fun getCardInfoList(artist: String): List<Card>
```

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/CardDataBase.kt
> +            val cardList: MutableList<Card> = executeGetCardInfoList(artist)
```suggestion
            val cardList = executeGetCardInfoList(artist)
```

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/CardDataBase.kt
> +            mutableListOf()
```suggestion
            listOf()
```

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/database/CardDataBase.kt
> +    private fun executeGetCardInfoList(artist: String): MutableList<Card> {
```suggestion
    private fun executeGetCardInfoList(artist: String): List<Card> {
```

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +    val cardsUiStates: MutableList<CardUiState>
Deben manejar una lista de cards, no de CardUIState y además deberia estar como property del UIState

```
CardUIState(
  val windowTitle: String = "Song Info Hera",
  val artistName: String = "",
  ...
) {
   val cards: List<Card> = listOf() 
}
```

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +
Linea de más

2021-07-06 23:50 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +        updateCardPreview(newState)
Fijense que si hacen un update del UIState antes, cada uno de estos métodos no requiere el parámetro, ya que todos tienen acceso al UIState

2021-07-07 01:34 UTC, TomasDiez99 commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +        updateCardPreview(newState)
Habia otra anotación en la que nos decías que desde el evento de Next actualicemos los componentes de GUI directamente con la siguiente Card, sin pasar por un metodo cascara del controller. Entonces hicimos que llame a updateGUIComponents con nextCard() como parametro, que devuelve directamente la siguiente Card de la lista de uiState. El problema es que hace que tengamos como parametro local en este metodo a una Card. Lo que nos pediste es que este metodo trabaje directamente sin parámetros o que no trabaje con un state solamente? La otra solucion que podríamos hacer es que cuando se activa el evento Next, hagamos en dos líneas un nextCard() de uiState y luego llamar a updateGUIComponents sin ningun parametro, haciendo que el metodo trabaje siempre con el currentIndex independientemente de quien lo llamó

2021-07-08 17:37 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyLastFMData.kt
> +    private fun mapCard(artistName: String): Card? {
Esto no esta solo mapeando. La llamada al service deberia estar en getCard() y a su resultado deberian mandarselo al metodo map. Tambien pued hacer una extension function de Article que se llame mapToCard(), especial para ejemplo de extension function ya que uds no tienen acceso a Article

2021-07-08 17:37 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyNYTimesData.kt
> +    private fun mapCard(artistName: String): Card? {
mismo que arriba

2021-07-08 17:37 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyWikipediaData.kt
> +    private fun mapCard(artistName: String): Card? {
mismo que arriba

2021-07-08 17:37 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/CardUiState.kt
> +        return cardList[currentCardIndex]
return currentCard() ya que es el mismo acceso

2021-07-08 17:37 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +    override fun updateGuiComponents(card: Card) {
Todo lo que esta dentro de esta clase tiene acceso a la UIState por lo tanto pasar por parametros no seria necesario. Entiendo que lo hacen porque le mandan la nextCard desde el controller. Pueden hacer lo siguiente:

- El metodo nextCard() cambienlo para que solo actualice el indice pero no retorne nada
- updateGuiComponents no recibe parametros y cada uno de sus subfunciones tampoco, ya que van a acceder a uiState.currentCard() ya que el indice fue actualizado antes

2021-07-08 17:37 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUIView.kt
> +        updateCardPreview(newState)
Recien lo veo. Les deje un comentario al respecto.

2021-07-12 11:51 UTC, kevschweitzer requested changes

2021-07-12 11:51 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyLastFMData.kt
> +        val lastFMCard = lastFmDataService.getCardInfo(artistName)
Lo que viene del servicio no es un card asi que seria mejor otro nombre como `lastFMArticle`. Sino despues queda `lastFMCard.mapToCard()`

2021-07-12 11:51 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyLastFMData.kt
> +        if ((lastFMCard == null) || (lastFMCard is EmptyArticle)) return null
Usar el return if
```suggestion
       return if ((lastFMCard == null) || (lastFMCard is EmptyArticle))
           null
       else
           lastFMArticle.mapToCard()
```

2021-07-12 11:51 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyNYTimesData.kt
> +        return nyTimesDataService.getArticle(artistName)?.mapToCard() ?: return null
el segundo return no hace falta

2021-07-12 11:51 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyWikipediaData.kt
> +        return wikipediaService.getArtistInfo(artistName)?.mapToCard() ?: return null
El segundo return no hace falta

2021-07-12 11:51 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/CardToSourceStringFactory.kt
>      override fun get(card: Card): CardToSourceStringMapper =
Ya que solo necesitan el source podrían pasar solo el source de la card y no la card entera como parámetro, y cambiarle el nombre a SourceToStringFactory

2021-07-12 11:51 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/CardUiState.kt
> +
Linea de más

2021-07-12 11:51 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/CardUiState.kt
> +    fun currentCard(): Card {
ponganle `getCurrentCard()` sino por el formato de nombre que tienen se puede asumir a simple vista que nextCard y currentCard() deberian tener retornos parecidos lo cual no es asi

2021-07-12 14:22 UTC, kevschweitzer requested changes

2021-07-12 14:22 UTC, kevschweitzer commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/CardToSourceStringFactory.kt
>  interface CardToSourceStringFactory {
Me referia a renombrar este factory como `SoruceToStringFactory` ya que ahora recibe un source y no una card. Los mappers tambien estaria bien cambiarlos de nombre pero a `SourceToStringMapper`

2021-07-12 15:02 UTC, kevschweitzer approved these changes

2021-07-12 15:02 UTC, merged